### ISSUE TITLE
Keep and host documentation/test coverage some other place.

### ISSUE THREAD

**Issue by roobie** [BoolNordicAB/sharepoint-utilities#19]
Not very nice to have so much more diffs than necessary.

**Comment by roobie** [comment]
use https://travis-ci.org/ and integrate https://coveralls.io, perhaps

**Comment by boolnordic** [comment]
We now have Travis CI! https://github.com/BoolNordicAB/sharepoint-utilities/commit/0acc4b222a869a95e891875e7e8e2e69538d8155

**Comment by roobie** [comment]
maybe put gh-pages to use

**Comment by roobie** [comment]
added `gh-pages` and links to it here https://github.com/BoolNordicAB/sharepoint-utilities/commit/73333dcdf17449c4215378a189d3f1247b544f8d
