### ISSUE TITLE
Document checkFile

### ISSUE THREAD

**Issue by eakron** [BoolNordicAB/sharepoint-utilities#25]
Needs documentation and better variable names (checkFile also not great name)

https://github.com/BoolNordicAB/sharepoint-utilities/blob/master/src/sputils.list.js#L57

**Comment by roobie** [comment]
I agree it needs more documentation. However I think the name is good because the usage is:

    checkFile('in', url).then(...

ie. I think it reads fine when used. But more doc solves that, yes?

**Comment by roobie** [comment]
All right, I'll make it so:
```
sputils.list.files.checkIn(url) // => Promise;
sputils.list.files.checkOut(url) // => Promise;
```
