### ISSUE TITLE
ReferenceError fjs

### ISSUE THREAD

**Issue by mirontoli** [BoolNordicAB/sharepoint-utilities#36]
A really good utiltiy framework. I can build it, but when I run tests, I get this error:

PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: fjs

![image](https://cloud.githubusercontent.com/assets/470105/13898963/babf3bba-ede2-11e5-8b7e-93c0263093e8.png)

Just for information, I installed these three npm packages (because the were missing):
npm install mocha chai fjs

The error is on line 29 in the file sputils.list.files.js
```javascript
sputils.list = fjs.assign(sputils.list || {},
```

@eakron @roobie

**Comment by roobie** [comment]
I'll check it out. Also, in order for this to never happen again, I'll add husky and a `prepush` hook that runs the tests, so that this kind of silly errors are caught before being pushed to the repo.

**Comment by roobie** [comment]
I could reproduce this prior to running `bower install`. After installing the bower components, the error disappeared, so I'm guessing that is the cause. I'll add a `pretest` clause in package.json, which will mitigate this.

**Comment by mirontoli** [comment]
Thank you!
