### ISSUE TITLE
One last check

### ISSUE THREAD

**Issue by roobie** [BoolNordicAB/sharepoint-utilities#41]
Peruse the API and double check the following:

- [X] **module and function names**. They should have descriptive names that, as much as possible, relates to what they actually do.
- [X] **documentation**. Are exported variables sufficiently documented?

**Comment by roobie** [comment]
My opinion is that the library is sufficiently revised, in its current state. However, I would really like @mirontoli and/or other @BoolNordicAB/members (or anyone, really) to chime in.

**Comment by mirontoli** [comment]
Hi, I think it is really good. I use sputils in a project. It works very good.

**Comment by mirontoli** [comment]
Shouldn't we label the released versions with version numbers? Like 1.0 and so?

**Comment by roobie** [comment]
@mirontoli yes we will. I think you should be able to see under releases that I've created a draft for 1.0.0-RC1, which I'm thinking about publishing soon. If we cannot discover right now that we have more refactors or tests to do, I'm all for publishing that release. This will cause the current latest commit of master to be tagged in git, in order for us to keep track of the releases.

**Comment by roobie** [comment]
I'll close this then, if nobody disagrees
