### ISSUE TITLE
sputils.list does not pass tests

### ISSUE THREAD

**Issue by mirontoli** [BoolNordicAB/sharepoint-utilities#45]
When I run ```npm test``` I get these warnings:

![image](https://cloud.githubusercontent.com/assets/470105/15302880/7f5a3cea-1bb5-11e6-83ab-6a7ef5b0d291.png)

**Comment by roobie** [comment]
I can't repro by using `npm test` but if I use `jscs` directly, I get the errors too. I'll update the jscs rc to ignore this tag (even though it does exist http://usejsdoc.org/tags-memberof.html)

**Comment by roobie** [comment]
@mirontoli was it fixed for you? Otherwise reopen, please :smiley:
